***Задание на повторение материала***

In [2]:
import numpy as np

1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [5]:
a = np.arange (12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

-

3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

-

4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

Нет.
Если у массива задано и количество столбцов, и количество строк, то он будет считаться двумерным.

5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [44]:
a = np.random.randn (3, 4)
a

array([[ 0.869593  ,  0.44226366,  0.33625289, -0.46185301],
       [-1.10487527,  1.78056676,  0.20441428, -0.22947304],
       [-0.01229403,  0.32921553,  1.34423776,  0.20198166]])

In [45]:
a.size

12

In [51]:
b = a.reshape (a.size, 1)

In [52]:
b.size

12

6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [17]:
a = np.arange (20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [14]:
b = np.arange (20, 1, -2)
b

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [15]:
a.shape == b.shape

True

In [16]:
a.size == b.size

True

In [18]:
a.ndim == b.ndim

True

Если создавать массив b вручную, то разница никакой не будет.
А если создавать новый массив (с) с использоваанием reshape, получим разные массивы. 
Массив a представляет собой одномерную "конструкцию" длиной 10.

In [20]:
c = a.reshape (1, 10)
c

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [21]:
a.shape == c.shape

False

In [22]:
a.shape

(10,)

In [23]:
a.size == c.size

True

Массив a одномерный, а массив c — двумерный, хоть и состоит из одной строки.

In [24]:
a.ndim == c.ndim

False

In [25]:
a.ndim

1

In [26]:
c.ndim

2

8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [ ]:
Количество элементов в обоих массивах должно быть 10.
Чтобы объединить массивы по вертикали в них должно быть одинаковое количество столбцов.

line * column + (line + 1) * column = 10

In [39]:
a = np.zeros ((2,2))

In [40]:
b = np.ones ((3,2))

In [41]:
v = np.vstack ((a,b))
v.size

10

9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [58]:
a = np.arange (0,12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [74]:
A = a.reshape ((4,3))
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [75]:
At = A.transpose ()
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [76]:
B = A.dot (At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [77]:
B.size

16

In [78]:
Binv = np.linalg.inv(B)
Binv

LinAlgError: Singular matrix

In [79]:
Bdet = np.linalg.det(B)
Bdet

0.0

Определитель для матрицы B не удается посчитать потому что:
не смотря на то, что матрица B квадратная, определитель  матрицы равен нулю

10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [66]:
np.random.seed (42)

11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [70]:
c = np.random.randint (0, 16, 16)
c

array([ 9,  5, 12, 11,  8,  0, 10, 10, 14,  9, 15, 11, 11, 15, 14, 13])

12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [71]:
c.size

16

In [72]:
C = c.reshape (4,4)
C

array([[ 9,  5, 12, 11],
       [ 8,  0, 10, 10],
       [14,  9, 15, 11],
       [11, 15, 14, 13]])

In [82]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [81]:
D = B + C * 10
D

array([[ 95,  64, 143, 142],
       [ 94,  50, 186, 222],
       [163, 176, 299, 322],
       [142, 272, 352, 432]])

In [84]:
# определитель
Ddet = np.linalg.det(D)
Ddet

-6670799.99999999

In [85]:
# ранг
Drank = np.linalg.matrix_rank(D)
Drank

4

In [86]:
# оборатная матрица
Dinv = np.linalg.inv(D)
Dinv

array([[ 0.20411345, -0.01299994, -0.15029082,  0.05161   ],
       [ 0.0309618 , -0.01359357, -0.02117587,  0.01259219],
       [-0.29589854,  0.01036158,  0.24635726, -0.09168915],
       [ 0.1545152 ,  0.00438928, -0.13800144,  0.05213168]])

13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [94]:
i = 0
j = 0
for i in range (len(Dinv)):
    for j in range (len(Dinv[i])):
        if (Dinv[i][j] > 0):
            Dinv[i][j] = 1
        if (Dinv[i][j] < 0):
            Dinv[i][j] = 0
Dinv

array([[1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [1., 1., 0., 1.]])

In [96]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [97]:
C

array([[ 9,  5, 12, 11],
       [ 8,  0, 10, 10],
       [14,  9, 15, 11],
       [11, 15, 14, 13]])

In [95]:
E = np.where (Dinv == 1, B, C)
E

array([[  5,   5,  12,  32],
       [ 14,   0,  10, 122],
       [ 14,  86, 149,  11],
       [ 32, 122,  14, 302]])